import datetime
from tools import getWordsTime
from unittest import TestCase


def getWordsForTime(h, m):
    return getWordsTime(datetime.datetime(year=2000, month=6, day=6, hour=h, minute=m))


def test():
    assertEqual = TestCase().assertEqual
    assertEqual(getWordsForTime(11, 58), ['IL', 'EST', 'MIDI'])
    assertEqual(getWordsForTime(11, 59), ['IL', 'EST', 'MIDI'])
    assertEqual(getWordsForTime(12, 0), ['IL', 'EST', 'MIDI'])
    assertEqual(getWordsForTime(12, 1), ['IL', 'EST', 'MIDI'])
    assertEqual(getWordsForTime(12, 2), ['IL', 'EST', 'MIDI'])
    assertEqual(getWordsForTime(12, 3), ['IL', 'EST', 'MIDI', 'cINQ'])
    assertEqual(getWordsForTime(12, 8), ['IL', 'EST', 'MIDI', 'dIX'])
    assertEqual(getWordsForTime(12, 13), ['IL', 'EST', 'MIDI', 'QUART'])
    assertEqual(getWordsForTime(12, 18), ['IL', 'EST', 'MIDI', 'VINGT'])
    assertEqual(getWordsForTime(12, 23), ['IL', 'EST', 'MIDI', 'VINGT', 'cINQ'])
    assertEqual(getWordsForTime(12, 28), ['IL', 'EST', 'MIDI', 'TRENTE'])
    assertEqual(getWordsForTime(12, 33), ['IL', 'EST', 'MIDI', 'TRENTE', 'cINQ'])
    assertEqual(getWordsForTime(12, 38), ['IL', 'EST', 'UNE', 'HEURE', 'MOINS', 'VINGT'])
    assertEqual(getWordsForTime(12, 43), ['IL', 'EST', 'UNE', 'HEURE', 'MOINS', 'QUART'])
    assertEqual(getWordsForTime(12, 48), ['IL', 'EST', 'UNE', 'HEURE', 'MOINS', 'dIX'])
    assertEqual(getWordsForTime(12, 53), ['IL', 'EST', 'UNE', 'HEURE', 'MOINS', 'cINQ'])
    assertEqual(getWordsForTime(12, 58), ['IL', 'EST', 'UNE', 'HEURE'])
    assertEqual(getWordsForTime(13, 3), ['IL', 'EST', 'UNE', 'HEURE', 'cINQ'])
    assertEqual(getWordsForTime(13, 8), ['IL', 'EST', 'UNE', 'HEURE', 'dIX'])
    assertEqual(getWordsForTime(13, 13), ['IL', 'EST', 'UNE', 'HEURE', 'QUART'])
    assertEqual(getWordsForTime(13, 18), ['IL', 'EST', 'UNE', 'HEURE', 'VINGT'])
    assertEqual(getWordsForTime(13, 23), ['IL', 'EST', 'UNE', 'HEURE', 'VINGT', 'cINQ'])
    assertEqual(getWordsForTime(13, 28), ['IL', 'EST', 'UNE', 'HEURE', 'TRENTE'])
    assertEqual(getWordsForTime(13, 33), ['IL', 'EST', 'UNE', 'HEURE', 'TRENTE', 'cINQ'])
    assertEqual(getWordsForTime(13, 34), ['IL', 'EST', 'UNE', 'HEURE', 'TRENTE', 'cINQ'])
    assertEqual(getWordsForTime(13, 35), ['IL', 'EST', 'UNE', 'HEURE', 'TRENTE', 'cINQ'])
    assertEqual(getWordsForTime(13, 36), ['IL', 'EST', 'UNE', 'HEURE', 'TRENTE', 'cINQ'])
    assertEqual(getWordsForTime(13, 38), ['IL', 'EST', 'DEUX', 'HEURES', 'MOINS', 'VINGT'])
    assertEqual(getWordsForTime(13, 43), ['IL', 'EST', 'DEUX', 'HEURES', 'MOINS', 'QUART'])
    assertEqual(getWordsForTime(13, 48), ['IL', 'EST', 'DEUX', 'HEURES', 'MOINS', 'dIX'])
    assertEqual(getWordsForTime(13, 53), ['IL', 'EST', 'DEUX', 'HEURES', 'MOINS', 'cINQ'])
    assertEqual(getWordsForTime(13, 58), ['IL', 'EST', 'DEUX', 'HEURES'])
    assertEqual(getWordsForTime(14, 3), ['IL', 'EST', 'DEUX', 'HEURES', 'cINQ'])
    assertEqual(getWordsForTime(14, 8), ['IL', 'EST', 'DEUX', 'HEURES', 'dIX'])
    assertEqual(getWordsForTime(14, 13), ['IL', 'EST', 'DEUX', 'HEURES', 'QUART'])
    assertEqual(getWordsForTime(14, 18), ['IL', 'EST', 'DEUX', 'HEURES', 'VINGT'])
    assertEqual(getWordsForTime(14, 23), ['IL', 'EST', 'DEUX', 'HEURES', 'VINGT', 'cINQ'])
    assertEqual(getWordsForTime(14, 28), ['IL', 'EST', 'DEUX', 'HEURES', 'TRENTE'])
    assertEqual(getWordsForTime(14, 33), ['IL', 'EST', 'DEUX', 'HEURES', 'TRENTE', 'cINQ'])
    assertEqual(getWordsForTime(14, 38), ['IL', 'EST', 'TROIS', 'HEURES', 'MOINS', 'VINGT'])
    assertEqual(getWordsForTime(14, 43), ['IL', 'EST', 'TROIS', 'HEURES', 'MOINS', 'QUART'])
    assertEqual(getWordsForTime(14, 48), ['IL', 'EST', 'TROIS', 'HEURES', 'MOINS', 'dIX'])
    assertEqual(getWordsForTime(14, 53), ['IL', 'EST', 'TROIS', 'HEURES', 'MOINS', 'cINQ'])
    assertEqual(getWordsForTime(14, 58), ['IL', 'EST', 'TROIS', 'HEURES'])
    assertEqual(getWordsForTime(15, 3), ['IL', 'EST', 'TROIS', 'HEURES', 'cINQ'])
    assertEqual(getWordsForTime(15, 8), ['IL', 'EST', 'TROIS', 'HEURES', 'dIX'])
    assertEqual(getWordsForTime(15, 13), ['IL', 'EST', 'TROIS', 'HEURES', 'QUART'])
    assertEqual(getWordsForTime(15, 18), ['IL', 'EST', 'TROIS', 'HEURES', 'VINGT'])
    assertEqual(getWordsForTime(15, 23), ['IL', 'EST', 'TROIS', 'HEURES', 'VINGT', 'cINQ'])
    assertEqual(getWordsForTime(15, 28), ['IL', 'EST', 'TROIS', 'HEURES', 'TRENTE'])
    assertEqual(getWordsForTime(15, 33), ['IL', 'EST', 'TROIS', 'HEURES', 'TRENTE', 'cINQ'])
    assertEqual(getWordsForTime(15, 38), ['IL', 'EST', 'QUATRE', 'HEURES', 'MOINS', 'VINGT'])
    assertEqual(getWordsForTime(15, 43), ['IL', 'EST', 'QUATRE', 'HEURES', 'MOINS', 'QUART'])
    assertEqual(getWordsForTime(15, 48), ['IL', 'EST', 'QUATRE', 'HEURES', 'MOINS', 'dIX'])
    assertEqual(getWordsForTime(15, 53), ['IL', 'EST', 'QUATRE', 'HEURES', 'MOINS', 'cINQ'])
    assertEqual(getWordsForTime(15, 58), ['IL', 'EST', 'QUATRE', 'HEURES'])
    assertEqual(getWordsForTime(16, 2), ['IL', 'EST', 'QUATRE', 'HEURES'])
    assertEqual(getWordsForTime(16, 3), ['IL', 'EST', 'QUATRE', 'HEURES', 'cINQ'])
    assertEqual(getWordsForTime(16, 8), ['IL', 'EST', 'QUATRE', 'HEURES', 'dIX'])
    assertEqual(getWordsForTime(16, 13), ['IL', 'EST', 'QUATRE', 'HEURES', 'QUART'])
    assertEqual(getWordsForTime(16, 18), ['IL', 'EST', 'QUATRE', 'HEURES', 'VINGT'])
    assertEqual(getWordsForTime(16, 23), ['IL', 'EST', 'QUATRE', 'HEURES', 'VINGT', 'cINQ'])
    assertEqual(getWordsForTime(16, 28), ['IL', 'EST', 'QUATRE', 'HEURES', 'TRENTE'])
    assertEqual(getWordsForTime(16, 33), ['IL', 'EST', 'QUATRE', 'HEURES', 'TRENTE', 'cINQ'])
    assertEqual(getWordsForTime(16, 38), ['IL', 'EST', 'CINQ', 'HEURES', 'MOINS', 'VINGT'])
    assertEqual(getWordsForTime(16, 43), ['IL', 'EST', 'CINQ', 'HEURES', 'MOINS', 'QUART'])
    assertEqual(getWordsForTime(16, 48), ['IL', 'EST', 'CINQ', 'HEURES', 'MOINS', 'dIX'])
    assertEqual(getWordsForTime(16, 53), ['IL', 'EST', 'CINQ', 'HEURES', 'MOINS', 'cINQ'])
    assertEqual(getWordsForTime(16, 58), ['IL', 'EST', 'CINQ', 'HEURES'])
    assertEqual(getWordsForTime(17, 3), ['IL', 'EST', 'CINQ', 'HEURES', 'cINQ'])
    assertEqual(getWordsForTime(17, 8), ['IL', 'EST', 'CINQ', 'HEURES', 'dIX'])
    assertEqual(getWordsForTime(17, 13), ['IL', 'EST', 'CINQ', 'HEURES', 'QUART'])
    assertEqual(getWordsForTime(17, 18), ['IL', 'EST', 'CINQ', 'HEURES', 'VINGT'])
    assertEqual(getWordsForTime(17, 23), ['IL', 'EST', 'CINQ', 'HEURES', 'VINGT', 'cINQ'])
    assertEqual(getWordsForTime(17, 28), ['IL', 'EST', 'CINQ', 'HEURES', 'TRENTE'])
    assertEqual(getWordsForTime(17, 33), ['IL', 'EST', 'CINQ', 'HEURES', 'TRENTE', 'cINQ'])
    assertEqual(getWordsForTime(17, 38), ['IL', 'EST', 'SIX', 'HEURES', 'MOINS', 'VINGT'])
    assertEqual(getWordsForTime(17, 43), ['IL', 'EST', 'SIX', 'HEURES', 'MOINS', 'QUART'])
    assertEqual(getWordsForTime(17, 48), ['IL', 'EST', 'SIX', 'HEURES', 'MOINS', 'dIX'])
    assertEqual(getWordsForTime(17, 53), ['IL', 'EST', 'SIX', 'HEURES', 'MOINS', 'cINQ'])
    assertEqual(getWordsForTime(17, 58), ['IL', 'EST', 'SIX', 'HEURES'])
    assertEqual(getWordsForTime(18, 3), ['IL', 'EST', 'SIX', 'HEURES', 'cINQ'])
    assertEqual(getWordsForTime(18, 8), ['IL', 'EST', 'SIX', 'HEURES', 'dIX'])
    assertEqual(getWordsForTime(18, 13), ['IL', 'EST', 'SIX', 'HEURES', 'QUART'])
    assertEqual(getWordsForTime(18, 18), ['IL', 'EST', 'SIX', 'HEURES', 'VINGT'])
    assertEqual(getWordsForTime(18, 23), ['IL', 'EST', 'SIX', 'HEURES', 'VINGT', 'cINQ'])
    assertEqual(getWordsForTime(18, 28), ['IL', 'EST', 'SIX', 'HEURES', 'TRENTE'])
    assertEqual(getWordsForTime(18, 33), ['IL', 'EST', 'SIX', 'HEURES', 'TRENTE', 'cINQ'])
    assertEqual(getWordsForTime(18, 38), ['IL', 'EST', 'SEPT', 'HEURES', 'MOINS', 'VINGT'])
    assertEqual(getWordsForTime(18, 43), ['IL', 'EST', 'SEPT', 'HEURES', 'MOINS', 'QUART'])
    assertEqual(getWordsForTime(18, 48), ['IL', 'EST', 'SEPT', 'HEURES', 'MOINS', 'dIX'])
    assertEqual(getWordsForTime(18, 53), ['IL', 'EST', 'SEPT', 'HEURES', 'MOINS', 'cINQ'])
    assertEqual(getWordsForTime(18, 58), ['IL', 'EST', 'SEPT', 'HEURES'])
    assertEqual(getWordsForTime(19, 3), ['IL', 'EST', 'SEPT', 'HEURES', 'cINQ'])
    assertEqual(getWordsForTime(19, 8), ['IL', 'EST', 'SEPT', 'HEURES', 'dIX'])
    assertEqual(getWordsForTime(19, 13), ['IL', 'EST', 'SEPT', 'HEURES', 'QUART'])
    assertEqual(getWordsForTime(19, 18), ['IL', 'EST', 'SEPT', 'HEURES', 'VINGT'])
    assertEqual(getWordsForTime(19, 23), ['IL', 'EST', 'SEPT', 'HEURES', 'VINGT', 'cINQ'])
    assertEqual(getWordsForTime(19, 28), ['IL', 'EST', 'SEPT', 'HEURES', 'TRENTE'])
    assertEqual(getWordsForTime(19, 33), ['IL', 'EST', 'SEPT', 'HEURES', 'TRENTE', 'cINQ'])
    assertEqual(getWordsForTime(19, 38), ['IL', 'EST', 'HUIT', 'HEURES', 'MOINS', 'VINGT'])
    assertEqual(getWordsForTime(19, 43), ['IL', 'EST', 'HUIT', 'HEURES', 'MOINS', 'QUART'])
    assertEqual(getWordsForTime(19, 48), ['IL', 'EST', 'HUIT', 'HEURES', 'MOINS', 'dIX'])
    assertEqual(getWordsForTime(19, 53), ['IL', 'EST', 'HUIT', 'HEURES', 'MOINS', 'cINQ'])
    assertEqual(getWordsForTime(19, 58), ['IL', 'EST', 'HUIT', 'HEURES'])
    assertEqual(getWordsForTime(20, 3), ['IL', 'EST', 'HUIT', 'HEURES', 'cINQ'])
    assertEqual(getWordsForTime(20, 8), ['IL', 'EST', 'HUIT', 'HEURES', 'dIX'])
    assertEqual(getWordsForTime(20, 13), ['IL', 'EST', 'HUIT', 'HEURES', 'QUART'])
    assertEqual(getWordsForTime(20, 18), ['IL', 'EST', 'HUIT', 'HEURES', 'VINGT'])
    assertEqual(getWordsForTime(20, 23), ['IL', 'EST', 'HUIT', 'HEURES', 'VINGT', 'cINQ'])
    assertEqual(getWordsForTime(20, 28), ['IL', 'EST', 'HUIT', 'HEURES', 'TRENTE'])
    assertEqual(getWordsForTime(20, 33), ['IL', 'EST', 'HUIT', 'HEURES', 'TRENTE', 'cINQ'])
    assertEqual(getWordsForTime(20, 38), ['IL', 'EST', 'NEUF', 'HEURES', 'MOINS', 'VINGT'])
    assertEqual(getWordsForTime(20, 43), ['IL', 'EST', 'NEUF', 'HEURES', 'MOINS', 'QUART'])
    assertEqual(getWordsForTime(20, 48), ['IL', 'EST', 'NEUF', 'HEURES', 'MOINS', 'dIX'])
    assertEqual(getWordsForTime(20, 53), ['IL', 'EST', 'NEUF', 'HEURES', 'MOINS', 'cINQ'])
    assertEqual(getWordsForTime(20, 58), ['IL', 'EST', 'NEUF', 'HEURES'])
    assertEqual(getWordsForTime(21, 3), ['IL', 'EST', 'NEUF', 'HEURES', 'cINQ'])
    assertEqual(getWordsForTime(21, 8), ['IL', 'EST', 'NEUF', 'HEURES', 'dIX'])
    assertEqual(getWordsForTime(21, 13), ['IL', 'EST', 'NEUF', 'HEURES', 'QUART'])
    assertEqual(getWordsForTime(21, 18), ['IL', 'EST', 'NEUF', 'HEURES', 'VINGT'])
    assertEqual(getWordsForTime(21, 23), ['IL', 'EST', 'NEUF', 'HEURES', 'VINGT', 'cINQ'])
    assertEqual(getWordsForTime(21, 28), ['IL', 'EST', 'NEUF', 'HEURES', 'TRENTE'])
    assertEqual(getWordsForTime(21, 33), ['IL', 'EST', 'NEUF', 'HEURES', 'TRENTE', 'cINQ'])
    assertEqual(getWordsForTime(21, 38), ['IL', 'EST', 'DIX', 'HEURES', 'MOINS', 'VINGT'])
    assertEqual(getWordsForTime(21, 43), ['IL', 'EST', 'DIX', 'HEURES', 'MOINS', 'QUART'])
    assertEqual(getWordsForTime(21, 48), ['IL', 'EST', 'DIX', 'HEURES', 'MOINS', 'dIX'])
    assertEqual(getWordsForTime(21, 53), ['IL', 'EST', 'DIX', 'HEURES', 'MOINS', 'cINQ'])
    assertEqual(getWordsForTime(21, 58), ['IL', 'EST', 'DIX', 'HEURES'])
    assertEqual(getWordsForTime(22, 3), ['IL', 'EST', 'DIX', 'HEURES', 'cINQ'])
    assertEqual(getWordsForTime(22, 8), ['IL', 'EST', 'DIX', 'HEURES', 'dIX'])
    assertEqual(getWordsForTime(22, 13), ['IL', 'EST', 'DIX', 'HEURES', 'QUART'])
    assertEqual(getWordsForTime(22, 18), ['IL', 'EST', 'DIX', 'HEURES', 'VINGT'])
    assertEqual(getWordsForTime(22, 23), ['IL', 'EST', 'DIX', 'HEURES', 'VINGT', 'cINQ'])
    assertEqual(getWordsForTime(22, 28), ['IL', 'EST', 'DIX', 'HEURES', 'TRENTE'])
    assertEqual(getWordsForTime(22, 33), ['IL', 'EST', 'DIX', 'HEURES', 'TRENTE', 'cINQ'])
    assertEqual(getWordsForTime(22, 38), ['IL', 'EST', 'ONZE', 'HEURES', 'MOINS', 'VINGT'])
    assertEqual(getWordsForTime(22, 43), ['IL', 'EST', 'ONZE', 'HEURES', 'MOINS', 'QUART'])
    assertEqual(getWordsForTime(22, 48), ['IL', 'EST', 'ONZE', 'HEURES', 'MOINS', 'dIX'])
    assertEqual(getWordsForTime(22, 53), ['IL', 'EST', 'ONZE', 'HEURES', 'MOINS', 'cINQ'])
    assertEqual(getWordsForTime(22, 58), ['IL', 'EST', 'ONZE', 'HEURES'])
    assertEqual(getWordsForTime(23, 3), ['IL', 'EST', 'ONZE', 'HEURES', 'cINQ'])
    assertEqual(getWordsForTime(23, 8), ['IL', 'EST', 'ONZE', 'HEURES', 'dIX'])
    assertEqual(getWordsForTime(23, 13), ['IL', 'EST', 'ONZE', 'HEURES', 'QUART'])
    assertEqual(getWordsForTime(23, 18), ['IL', 'EST', 'ONZE', 'HEURES', 'VINGT'])
    assertEqual(getWordsForTime(23, 23), ['IL', 'EST', 'ONZE', 'HEURES', 'VINGT', 'cINQ'])
    assertEqual(getWordsForTime(23, 28), ['IL', 'EST', 'ONZE', 'HEURES', 'TRENTE'])
    assertEqual(getWordsForTime(23, 33), ['IL', 'EST', 'ONZE', 'HEURES', 'TRENTE', 'cINQ'])
    assertEqual(getWordsForTime(23, 38), ['IL', 'EST', 'MINUIT', 'MOINS', 'VINGT'])
    assertEqual(getWordsForTime(23, 43), ['IL', 'EST', 'MINUIT', 'MOINS', 'QUART'])
    assertEqual(getWordsForTime(23, 48), ['IL', 'EST', 'MINUIT', 'MOINS', 'dIX'])
    assertEqual(getWordsForTime(23, 53), ['IL', 'EST', 'MINUIT', 'MOINS', 'cINQ'])
    assertEqual(getWordsForTime(23, 58), ['IL', 'EST', 'MINUIT'])
    assertEqual(getWordsForTime(0, 3), ['IL', 'EST', 'MINUIT', 'cINQ'])
    assertEqual(getWordsForTime(0, 8), ['IL', 'EST', 'MINUIT', 'dIX'])
    assertEqual(getWordsForTime(0, 13), ['IL', 'EST', 'MINUIT', 'QUART'])
    assertEqual(getWordsForTime(0, 18), ['IL', 'EST', 'MINUIT', 'VINGT'])
    assertEqual(getWordsForTime(0, 23), ['IL', 'EST', 'MINUIT', 'VINGT', 'cINQ'])
    assertEqual(getWordsForTime(0, 28), ['IL', 'EST', 'MINUIT', 'TRENTE'])
    assertEqual(getWordsForTime(0, 33), ['IL', 'EST', 'MINUIT', 'TRENTE', 'cINQ'])
    assertEqual(getWordsForTime(0, 38), ['IL', 'EST', 'UNE', 'HEURE', 'MOINS', 'VINGT'])
    assertEqual(getWordsForTime(0, 43), ['IL', 'EST', 'UNE', 'HEURE', 'MOINS', 'QUART'])
    assertEqual(getWordsForTime(0, 48), ['IL', 'EST', 'UNE', 'HEURE', 'MOINS', 'dIX'])
    assertEqual(getWordsForTime(0, 53), ['IL', 'EST', 'UNE', 'HEURE', 'MOINS', 'cINQ'])
    assertEqual(getWordsForTime(0, 58), ['IL', 'EST', 'UNE', 'HEURE'])
    assertEqual(getWordsForTime(1, 3), ['IL', 'EST', 'UNE', 'HEURE', 'cINQ'])
    assertEqual(getWordsForTime(1, 8), ['IL', 'EST', 'UNE', 'HEURE', 'dIX'])
    assertEqual(getWordsForTime(1, 13), ['IL', 'EST', 'UNE', 'HEURE', 'QUART'])
    assertEqual(getWordsForTime(1, 18), ['IL', 'EST', 'UNE', 'HEURE', 'VINGT'])
    assertEqual(getWordsForTime(1, 23), ['IL', 'EST', 'UNE', 'HEURE', 'VINGT', 'cINQ'])
    assertEqual(getWordsForTime(1, 28), ['IL', 'EST', 'UNE', 'HEURE', 'TRENTE'])
    assertEqual(getWordsForTime(1, 33), ['IL', 'EST', 'UNE', 'HEURE', 'TRENTE', 'cINQ'])
    assertEqual(getWordsForTime(1, 38), ['IL', 'EST', 'DEUX', 'HEURES', 'MOINS', 'VINGT'])
    assertEqual(getWordsForTime(1, 43), ['IL', 'EST', 'DEUX', 'HEURES', 'MOINS', 'QUART'])
    assertEqual(getWordsForTime(1, 48), ['IL', 'EST', 'DEUX', 'HEURES', 'MOINS', 'dIX'])
    assertEqual(getWordsForTime(1, 53), ['IL', 'EST', 'DEUX', 'HEURES', 'MOINS', 'cINQ'])
    assertEqual(getWordsForTime(1, 58), ['IL', 'EST', 'DEUX', 'HEURES'])
    assertEqual(getWordsForTime(2, 3), ['IL', 'EST', 'DEUX', 'HEURES', 'cINQ'])
    assertEqual(getWordsForTime(2, 8), ['IL', 'EST', 'DEUX', 'HEURES', 'dIX'])
    assertEqual(getWordsForTime(2, 13), ['IL', 'EST', 'DEUX', 'HEURES', 'QUART'])
    assertEqual(getWordsForTime(2, 18), ['IL', 'EST', 'DEUX', 'HEURES', 'VINGT'])
    assertEqual(getWordsForTime(2, 23), ['IL', 'EST', 'DEUX', 'HEURES', 'VINGT', 'cINQ'])
    assertEqual(getWordsForTime(2, 28), ['IL', 'EST', 'DEUX', 'HEURES', 'TRENTE'])
    assertEqual(getWordsForTime(2, 33), ['IL', 'EST', 'DEUX', 'HEURES', 'TRENTE', 'cINQ'])
    assertEqual(getWordsForTime(2, 38), ['IL', 'EST', 'TROIS', 'HEURES', 'MOINS', 'VINGT'])
    assertEqual(getWordsForTime(2, 43), ['IL', 'EST', 'TROIS', 'HEURES', 'MOINS', 'QUART'])
    assertEqual(getWordsForTime(2, 48), ['IL', 'EST', 'TROIS', 'HEURES', 'MOINS', 'dIX'])
    assertEqual(getWordsForTime(2, 53), ['IL', 'EST', 'TROIS', 'HEURES', 'MOINS', 'cINQ'])
    assertEqual(getWordsForTime(2, 58), ['IL', 'EST', 'TROIS', 'HEURES'])
    assertEqual(getWordsForTime(3, 3), ['IL', 'EST', 'TROIS', 'HEURES', 'cINQ'])
    assertEqual(getWordsForTime(3, 8), ['IL', 'EST', 'TROIS', 'HEURES', 'dIX'])
    assertEqual(getWordsForTime(3, 13), ['IL', 'EST', 'TROIS', 'HEURES', 'QUART'])
    assertEqual(getWordsForTime(3, 18), ['IL', 'EST', 'TROIS', 'HEURES', 'VINGT'])
    assertEqual(getWordsForTime(3, 23), ['IL', 'EST', 'TROIS', 'HEURES', 'VINGT', 'cINQ'])
    assertEqual(getWordsForTime(3, 28), ['IL', 'EST', 'TROIS', 'HEURES', 'TRENTE'])
    assertEqual(getWordsForTime(3, 33), ['IL', 'EST', 'TROIS', 'HEURES', 'TRENTE', 'cINQ'])
    assertEqual(getWordsForTime(3, 38), ['IL', 'EST', 'QUATRE', 'HEURES', 'MOINS', 'VINGT'])
    assertEqual(getWordsForTime(3, 43), ['IL', 'EST', 'QUATRE', 'HEURES', 'MOINS', 'QUART'])
    assertEqual(getWordsForTime(3, 48), ['IL', 'EST', 'QUATRE', 'HEURES', 'MOINS', 'dIX'])
    assertEqual(getWordsForTime(3, 53), ['IL', 'EST', 'QUATRE', 'HEURES', 'MOINS', 'cINQ'])
    assertEqual(getWordsForTime(3, 58), ['IL', 'EST', 'QUATRE', 'HEURES'])
    assertEqual(getWordsForTime(4, 3), ['IL', 'EST', 'QUATRE', 'HEURES', 'cINQ'])
    assertEqual(getWordsForTime(4, 8), ['IL', 'EST', 'QUATRE', 'HEURES', 'dIX'])
    assertEqual(getWordsForTime(4, 13), ['IL', 'EST', 'QUATRE', 'HEURES', 'QUART'])
    assertEqual(getWordsForTime(4, 18), ['IL', 'EST', 'QUATRE', 'HEURES', 'VINGT'])
    assertEqual(getWordsForTime(4, 23), ['IL', 'EST', 'QUATRE', 'HEURES', 'VINGT', 'cINQ'])
    assertEqual(getWordsForTime(4, 28), ['IL', 'EST', 'QUATRE', 'HEURES', 'TRENTE'])
    assertEqual(getWordsForTime(4, 33), ['IL', 'EST', 'QUATRE', 'HEURES', 'TRENTE', 'cINQ'])
    assertEqual(getWordsForTime(4, 38), ['IL', 'EST', 'CINQ', 'HEURES', 'MOINS', 'VINGT'])
    assertEqual(getWordsForTime(4, 43), ['IL', 'EST', 'CINQ', 'HEURES', 'MOINS', 'QUART'])
    assertEqual(getWordsForTime(4, 48), ['IL', 'EST', 'CINQ', 'HEURES', 'MOINS', 'dIX'])
    assertEqual(getWordsForTime(4, 53), ['IL', 'EST', 'CINQ', 'HEURES', 'MOINS', 'cINQ'])
    assertEqual(getWordsForTime(4, 58), ['IL', 'EST', 'CINQ', 'HEURES'])
    assertEqual(getWordsForTime(5, 3), ['IL', 'EST', 'CINQ', 'HEURES', 'cINQ'])
    assertEqual(getWordsForTime(5, 8), ['IL', 'EST', 'CINQ', 'HEURES', 'dIX'])
    assertEqual(getWordsForTime(5, 13), ['IL', 'EST', 'CINQ', 'HEURES', 'QUART'])
    assertEqual(getWordsForTime(5, 18), ['IL', 'EST', 'CINQ', 'HEURES', 'VINGT'])
    assertEqual(getWordsForTime(5, 23), ['IL', 'EST', 'CINQ', 'HEURES', 'VINGT', 'cINQ'])
    assertEqual(getWordsForTime(5, 28), ['IL', 'EST', 'CINQ', 'HEURES', 'TRENTE'])
    assertEqual(getWordsForTime(5, 33), ['IL', 'EST', 'CINQ', 'HEURES', 'TRENTE', 'cINQ'])
    assertEqual(getWordsForTime(5, 38), ['IL', 'EST', 'SIX', 'HEURES', 'MOINS', 'VINGT'])
    assertEqual(getWordsForTime(5, 43), ['IL', 'EST', 'SIX', 'HEURES', 'MOINS', 'QUART'])
    assertEqual(getWordsForTime(5, 48), ['IL', 'EST', 'SIX', 'HEURES', 'MOINS', 'dIX'])
    assertEqual(getWordsForTime(5, 53), ['IL', 'EST', 'SIX', 'HEURES', 'MOINS', 'cINQ'])
    assertEqual(getWordsForTime(5, 58), ['IL', 'EST', 'SIX', 'HEURES'])
    assertEqual(getWordsForTime(6, 3), ['IL', 'EST', 'SIX', 'HEURES', 'cINQ'])
    assertEqual(getWordsForTime(6, 8), ['IL', 'EST', 'SIX', 'HEURES', 'dIX'])
    assertEqual(getWordsForTime(6, 13), ['IL', 'EST', 'SIX', 'HEURES', 'QUART'])
    assertEqual(getWordsForTime(6, 18), ['IL', 'EST', 'SIX', 'HEURES', 'VINGT'])
    assertEqual(getWordsForTime(6, 23), ['IL', 'EST', 'SIX', 'HEURES', 'VINGT', 'cINQ'])
    assertEqual(getWordsForTime(6, 28), ['IL', 'EST', 'SIX', 'HEURES', 'TRENTE'])
    assertEqual(getWordsForTime(6, 33), ['IL', 'EST', 'SIX', 'HEURES', 'TRENTE', 'cINQ'])
    assertEqual(getWordsForTime(6, 38), ['IL', 'EST', 'SEPT', 'HEURES', 'MOINS', 'VINGT'])
    assertEqual(getWordsForTime(6, 43), ['IL', 'EST', 'SEPT', 'HEURES', 'MOINS', 'QUART'])
    assertEqual(getWordsForTime(6, 48), ['IL', 'EST', 'SEPT', 'HEURES', 'MOINS', 'dIX'])
    assertEqual(getWordsForTime(6, 53), ['IL', 'EST', 'SEPT', 'HEURES', 'MOINS', 'cINQ'])
    assertEqual(getWordsForTime(6, 58), ['IL', 'EST', 'SEPT', 'HEURES'])
    assertEqual(getWordsForTime(7, 3), ['IL', 'EST', 'SEPT', 'HEURES', 'cINQ'])
    assertEqual(getWordsForTime(7, 8), ['IL', 'EST', 'SEPT', 'HEURES', 'dIX'])
    assertEqual(getWordsForTime(7, 13), ['IL', 'EST', 'SEPT', 'HEURES', 'QUART'])
    assertEqual(getWordsForTime(7, 18), ['IL', 'EST', 'SEPT', 'HEURES', 'VINGT'])
    assertEqual(getWordsForTime(7, 23), ['IL', 'EST', 'SEPT', 'HEURES', 'VINGT', 'cINQ'])
    assertEqual(getWordsForTime(7, 28), ['IL', 'EST', 'SEPT', 'HEURES', 'TRENTE'])
    assertEqual(getWordsForTime(7, 33), ['IL', 'EST', 'SEPT', 'HEURES', 'TRENTE', 'cINQ'])
    assertEqual(getWordsForTime(7, 38), ['IL', 'EST', 'HUIT', 'HEURES', 'MOINS', 'VINGT'])
    assertEqual(getWordsForTime(7, 43), ['IL', 'EST', 'HUIT', 'HEURES', 'MOINS', 'QUART'])
    assertEqual(getWordsForTime(7, 48), ['IL', 'EST', 'HUIT', 'HEURES', 'MOINS', 'dIX'])
    assertEqual(getWordsForTime(7, 53), ['IL', 'EST', 'HUIT', 'HEURES', 'MOINS', 'cINQ'])
    assertEqual(getWordsForTime(7, 58), ['IL', 'EST', 'HUIT', 'HEURES'])
    assertEqual(getWordsForTime(8, 3), ['IL', 'EST', 'HUIT', 'HEURES', 'cINQ'])
    assertEqual(getWordsForTime(8, 8), ['IL', 'EST', 'HUIT', 'HEURES', 'dIX'])
    assertEqual(getWordsForTime(8, 13), ['IL', 'EST', 'HUIT', 'HEURES', 'QUART'])
    assertEqual(getWordsForTime(8, 18), ['IL', 'EST', 'HUIT', 'HEURES', 'VINGT'])
    assertEqual(getWordsForTime(8, 23), ['IL', 'EST', 'HUIT', 'HEURES', 'VINGT', 'cINQ'])
    assertEqual(getWordsForTime(8, 28), ['IL', 'EST', 'HUIT', 'HEURES', 'TRENTE'])
    assertEqual(getWordsForTime(8, 33), ['IL', 'EST', 'HUIT', 'HEURES', 'TRENTE', 'cINQ'])
    assertEqual(getWordsForTime(8, 38), ['IL', 'EST', 'NEUF', 'HEURES', 'MOINS', 'VINGT'])
    assertEqual(getWordsForTime(8, 43), ['IL', 'EST', 'NEUF', 'HEURES', 'MOINS', 'QUART'])
    assertEqual(getWordsForTime(8, 48), ['IL', 'EST', 'NEUF', 'HEURES', 'MOINS', 'dIX'])
    assertEqual(getWordsForTime(8, 53), ['IL', 'EST', 'NEUF', 'HEURES', 'MOINS', 'cINQ'])
    assertEqual(getWordsForTime(8, 58), ['IL', 'EST', 'NEUF', 'HEURES'])
    assertEqual(getWordsForTime(9, 3), ['IL', 'EST', 'NEUF', 'HEURES', 'cINQ'])
    assertEqual(getWordsForTime(9, 8), ['IL', 'EST', 'NEUF', 'HEURES', 'dIX'])
    assertEqual(getWordsForTime(9, 13), ['IL', 'EST', 'NEUF', 'HEURES', 'QUART'])
    assertEqual(getWordsForTime(9, 18), ['IL', 'EST', 'NEUF', 'HEURES', 'VINGT'])
    assertEqual(getWordsForTime(9, 23), ['IL', 'EST', 'NEUF', 'HEURES', 'VINGT', 'cINQ'])
    assertEqual(getWordsForTime(9, 28), ['IL', 'EST', 'NEUF', 'HEURES', 'TRENTE'])
    assertEqual(getWordsForTime(9, 33), ['IL', 'EST', 'NEUF', 'HEURES', 'TRENTE', 'cINQ'])
    assertEqual(getWordsForTime(9, 38), ['IL', 'EST', 'DIX', 'HEURES', 'MOINS', 'VINGT'])
    assertEqual(getWordsForTime(9, 43), ['IL', 'EST', 'DIX', 'HEURES', 'MOINS', 'QUART'])
    assertEqual(getWordsForTime(9, 48), ['IL', 'EST', 'DIX', 'HEURES', 'MOINS', 'dIX'])
    assertEqual(getWordsForTime(9, 53), ['IL', 'EST', 'DIX', 'HEURES', 'MOINS', 'cINQ'])
    assertEqual(getWordsForTime(9, 58), ['IL', 'EST', 'DIX', 'HEURES'])
    assertEqual(getWordsForTime(10, 3), ['IL', 'EST', 'DIX', 'HEURES', 'cINQ'])
    assertEqual(getWordsForTime(10, 8), ['IL', 'EST', 'DIX', 'HEURES', 'dIX'])
    assertEqual(getWordsForTime(10, 13), ['IL', 'EST', 'DIX', 'HEURES', 'QUART'])
    assertEqual(getWordsForTime(10, 18), ['IL', 'EST', 'DIX', 'HEURES', 'VINGT'])
    assertEqual(getWordsForTime(10, 23), ['IL', 'EST', 'DIX', 'HEURES', 'VINGT', 'cINQ'])
    assertEqual(getWordsForTime(10, 28), ['IL', 'EST', 'DIX', 'HEURES', 'TRENTE'])
    assertEqual(getWordsForTime(10, 33), ['IL', 'EST', 'DIX', 'HEURES', 'TRENTE', 'cINQ'])
    assertEqual(getWordsForTime(10, 38), ['IL', 'EST', 'ONZE', 'HEURES', 'MOINS', 'VINGT'])
    assertEqual(getWordsForTime(10, 43), ['IL', 'EST', 'ONZE', 'HEURES', 'MOINS', 'QUART'])
    assertEqual(getWordsForTime(10, 48), ['IL', 'EST', 'ONZE', 'HEURES', 'MOINS', 'dIX'])
    assertEqual(getWordsForTime(10, 53), ['IL', 'EST', 'ONZE', 'HEURES', 'MOINS', 'cINQ'])
    assertEqual(getWordsForTime(10, 58), ['IL', 'EST', 'ONZE', 'HEURES'])
    assertEqual(getWordsForTime(11, 3), ['IL', 'EST', 'ONZE', 'HEURES', 'cINQ'])
    assertEqual(getWordsForTime(11, 8), ['IL', 'EST', 'ONZE', 'HEURES', 'dIX'])
    assertEqual(getWordsForTime(11, 13), ['IL', 'EST', 'ONZE', 'HEURES', 'QUART'])
    assertEqual(getWordsForTime(11, 18), ['IL', 'EST', 'ONZE', 'HEURES', 'VINGT'])
    assertEqual(getWordsForTime(11, 23), ['IL', 'EST', 'ONZE', 'HEURES', 'VINGT', 'cINQ'])
    assertEqual(getWordsForTime(11, 28), ['IL', 'EST', 'ONZE', 'HEURES', 'TRENTE'])
    assertEqual(getWordsForTime(11, 33), ['IL', 'EST', 'ONZE', 'HEURES', 'TRENTE', 'cINQ'])
    assertEqual(getWordsForTime(11, 38), ['IL', 'EST', 'MIDI', 'MOINS', 'VINGT'])
    assertEqual(getWordsForTime(11, 43), ['IL', 'EST', 'MIDI', 'MOINS', 'QUART'])
    assertEqual(getWordsForTime(11, 48), ['IL', 'EST', 'MIDI', 'MOINS', 'dIX'])
    assertEqual(getWordsForTime(11, 53), ['IL', 'EST', 'MIDI', 'MOINS', 'cINQ'])


test()
